### ISSUE TITLE
security: SecKeychainItemImport: MAC verification failed during PKCS12 import (wrong password?)

### ISSUE THREAD

**Issue by anka-213** [bitrise-steplib/steps-ios-auto-provision#125]
I get the error above, but I have no idea why. I don't see any place to put in a password in this step, so what is it talking about?

Here's a failing build: https://app.bitrise.io/build/19cf12746b8d60d8#?tab=log

**Comment by non-binary** [comment]
Hi @anka-213,

Do you have a password on your certificate?

**Comment by anka-213** [comment]
@non-binary I have only tried using tags, does that count as pull request or master-like?

**Comment by non-binary** [comment]
Hi @anka-213,

I'm not sure.

Can you please try master branch and let us know if that works?

**Comment by anka-213** [comment]
@non-binary I tried that now. No luck. The keys are also marked as available for pr, so it shouldn't matter.

**Comment by non-binary** [comment]
Hi @anka-213,

Thanks for trying this with me. Can you send a link to that build?

I'm off for the day but I will do some more investigating and follow-up tomorrow.

**Comment by anka-213** [comment]
https://app.bitrise.io/build/8144917a5b31031a#?tab=log

**Comment by non-binary** [comment]
Hi @anka-213,

A few things:

1. I don't see the certificate.p12 certificate file uploaded to the Codesigning section. Please upload one again. Maybe it was somehow lost.

2. I see `Certrificate_1.p12` in the logs which is also confusing because it is spelt wrong but it is not showing up in the Codesigning section.

So please try readding the certificate and send another build link.

**Comment by anka-213** [comment]
I removed all the certificates and re-added new ones and that resolved the issue.
